language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag reverseproxy mrhiep/reverseproxy:v3
  - docker tag udagram-api-feed mrhiep/udagram-api-feed:v3
  - docker tag udagram-api-user mrhiep/udagram-api-user:v3
  - docker tag udagram-frontend mrhiep/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mrhiep/reverseproxy:v3
  - docker push mrhiep/udagram-api-feed:v3
  - docker push mrhiep/udagram-api-user:v3
  - docker push mrhiep/udagram-frontend:local